"""create tables

Revision ID: 96492aa8d183
Revises: 1d2f8def959d
Create Date: 2025-12-24 12:46:07.731638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96492aa8d183'
down_revision: Union[str, Sequence[str], None] = '1d2f8def959d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdd_classes', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('pdd_classes', sa.Column('predicted_label', sa.String(), nullable=True))
    op.add_column('pdd_classes', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('pdd_classes', sa.Column('created_date', sa.DateTime(), autoincrement=True, nullable=True))
    op.drop_column('pdd_classes', 'title')
    op.drop_column('pdd_classes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdd_classes', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pdd_classes', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pdd_classes', 'created_date')
    op.drop_column('pdd_classes', 'confidence')
    op.drop_column('pdd_classes', 'predicted_label')
    op.drop_column('pdd_classes', 'image_url')
    # ### end Alembic commands ###
