"""create tables

Revision ID: d8e06fd3d720
Revises: fcc323cc1a24
Create Date: 2025-12-22 10:30:06.337594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e06fd3d720'
down_revision: Union[str, Sequence[str], None] = 'fcc323cc1a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profile', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.add_column('user_profile', sa.Column('last_name', sa.String(length=32), nullable=False))
    op.add_column('user_profile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'phone_number')
    op.drop_column('user_profile', 'age')
    op.drop_column('user_profile', 'last_name')
    op.drop_column('user_profile', 'first_name')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
